### ISSUE TITLE
'lz-string' module

### ISSUE THREAD

**Issue by kerrop33** [aceymer/courseplanner#4]
I have a problem with lz-string module:

> Error: Cannot find module 'lz-string'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (F:/Web/courseplannet/courseplanner-master2/**server/api/folder/folder.controller.js:12:23**)

The preview version without the new api route **folder** in server side is working flawless.
node `4.4.5`
npm : `2.15.5`

**Comment by aceymer** [comment]
Fixed in the newest version.
Remember to do a npm install (I forgot to add it in package.json in the last version, sorry)
